select * from cust;

-- What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from cust
group by gender;

-- which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from cust
where discount_applied = 'Yes' and purchase_amount>(select avg(purchase_amount) from cust);

-- Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, avg(review_rating) as 'Average product rating'
from cust
group by item_purchased;

--	Compare the average Purchase Amounts between Standard and Express Shipping?
select shipping_type, 
avg(purchase_amount) as Average_purchased_amount
from cust
where shipping_type in ('Standard','Express')
group by shipping_type;


-- Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non-subscriber?
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_Spend,
round(sum(purchase_amount),2) as Total_spend
from cust
group by subscription_status;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
100 * SUM(CASE when discount_applied = 'Yes' Then 1 else 0 end)/count(*) as discounnt_rate
from cust
group by item_purchased
order by discounnt_rate desc;

-- Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment.
-- case when (






-- What are the top 3 most purchased products from each category





-- Are customers who are repeat buyers( more than 5 previous purchases)also likely to subsribe?
select subscription_status,
count(customer_id) as repeat_buyers
from cust
where previous_purchases > 5
group by subscription_status;


-- What are the revenue contribution of each age group?

select age_group, 
sum(purchase_amount) as Revenue_contribution
from cust
group by age_group;


select * from cust;


